### ISSUE TITLE
Do something smart when config_path is NULL

### ISSUE THREAD

**Issue by rverdon** [sholsapp/gallocy#22]
If config_path is NULL [here](https://github.com/sholsapp/gallocy/blob/2532767003cd007b25c29a8c9bfbde8407065e92/gallocy/entrypoint.cpp#L106), then bad things happen.

**Comment by sholsapp** [comment]
Yeah, it's true. I can fix that.

**Comment by sholsapp** [comment]
Fixed in 4934668
